apiVersion: networking.serving.volcano.sh/v1alpha1
kind: ModelRoute
metadata:
  name: deepseek-simple
  namespace: default
spec:
  modelName: "deepseek-simple"
  parentRefs:
  # When Gateway and ModelRoute are in the same namespace, namespace is optional
  # When they are in different namespaces, namespace must be specified
  - name: kthena-gateway
    namespace: default  # Optional when same namespace, but explicit for clarity
  rules:
  - name: "default"
    targetModels:
    - modelServerName: "deepseek-r1-1-5b"
