name: Build and Push Helm Chart OCI Artifact
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
      - "v*.*.*-*" # support pre-release tag. For example, v1.2.3-alpha, v1.2.3-beta, v1.2.3-rc1
jobs:
  release:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # <-- CHANGE: Necessary to get the git commit hash for versioning

      - name: Determine chart version and tag
        id: version
        run: |
          # Check if triggered by a tag or main branch
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            # Extract version from tag, removing 'v' prefix
            VERSION=${GITHUB_REF#refs/tags/v}
            echo "is_tag=true" >> $GITHUB_OUTPUT
            echo "Building from tag: $VERSION"
          else
            # Main branch push - use latest as the version
            VERSION="0.0.0-main-$(date -u +'%Y%m%d%H%M%S')-$(git rev-parse --short HEAD)"
            echo "is_tag=false" >> $GITHUB_OUTPUT
            echo "Building from main branch with dev version: $VERSION"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Chart version: $VERSION"

      - name: Check if prerelease
        if: steps.version.outputs.is_tag == 'true'
        id: is_prerelease
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          if [[ "$VERSION" == *-* ]]; then
            echo "prerelease=true" >> $GITHUB_OUTPUT
            echo "This is a prerelease version: $VERSION"
          else
            echo "prerelease=false" >> $GITHUB_OUTPUT
            echo "This is a stable release version: $VERSION"
          fi

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.18.4 # Use a specific, stable version of Helm

      - name: Setup Crane
        uses: imjasonh/setup-crane@v0.4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Update chart and image versions
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          echo "Updating versions to: $VERSION"
          
          # Update main Chart.yaml
          sed -i "s/^version: .*/version: $VERSION/" charts/kthena/Chart.yaml
          sed -i "s/^appVersion: .*/appVersion: \"$VERSION\"/" charts/kthena/Chart.yaml
          
          # Update image tags in all subchart values.yaml files
          if [[ "${{ steps.version.outputs.is_tag }}" == "true" ]]; then
            find charts/kthena/charts -name "values.yaml" -exec sed -i "s/tag: latest/tag: $VERSION/g" {} \;
          fi
          
          echo "=== Updated Chart.yaml ==="
          cat charts/kthena/Chart.yaml

      - name: Build and Package Helm Chart
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          echo "Building and packaging version: $VERSION"
          
          helm dependency build ./charts/kthena
          helm package ./charts/kthena --version $VERSION --app-version $VERSION

      - name: Push to GHCR
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          helm push kthena-${VERSION}.tgz oci://ghcr.io/${REPO_OWNER}/charts

      - name: Apply 'latest' tag for main branch builds
        if: steps.version.outputs.is_tag == 'false'
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          SOURCE_CHART="ghcr.io/${REPO_OWNER}/charts/kthena:${VERSION}"
          
          echo "Tagging ${SOURCE_CHART} as 'latest'"
          crane tag "${SOURCE_CHART}" latest

      - name: Helm template manifest
        if: steps.version.outputs.is_tag == 'true'
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          helm template kthena ./charts/kthena --namespace kthena-system > kthena-install-${VERSION}.yaml
          cp kthena-install-${VERSION}.yaml kthena-install.yaml

      - name: Github Release
        if: steps.version.outputs.is_tag == 'true'
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            ./kthena-${{ steps.version.outputs.version }}.tgz
            ./kthena-install-${{ steps.version.outputs.version }}.yaml
            ./kthena-install.yaml
          prerelease: ${{ steps.is_prerelease.outputs.prerelease || 'false' }}

