name: Release
on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-*" # support pre-release tag. For example, v1.2.3-alpha, v1.2.3-beta, v1.2.3-rc1
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Extract version from tag
        id: version
        run: |
          # Extract version from tag, removing 'v' prefix
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"
      - name: install helm
        shell: bash
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: Update chart and image versions
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          echo "Updating versions to: $VERSION"
          
          # Update main Chart.yaml
          sed -i "s/^version: .*/version: $VERSION/" charts/kthena/Chart.yaml
          sed -i "s/^appVersion: .*/appVersion: \"$VERSION\"/" charts/kthena/Chart.yaml
          
          # Update image tags in all subchart values.yaml files
          find charts/kthena/charts -name "values.yaml" -exec sed -i "s/tag: latest/tag: $VERSION/g" {} \;
          
          # Verify changes
          echo "=== Updated Chart.yaml ==="
          cat charts/kthena/Chart.yaml
          echo "=== Updated subchart versions ==="
          grep -r "tag: $VERSION" charts/kthena/charts/*/values.yaml || true
      - name: Helm package
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          helm package ./charts/kthena
          mv kthena-${VERSION}.tgz kthena-helm-${VERSION}.tgz
      - name: Check if prerelease
        id: is_prerelease
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          if [[ "$VERSION" == *-* ]]; then
            echo "prerelease=true" >> $GITHUB_OUTPUT
            echo "This is a prerelease version: $VERSION"
          else
            echo "prerelease=false" >> $GITHUB_OUTPUT
            echo "This is a stable release version: $VERSION"
          fi
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: ${{ github.workspace }}/*.tgz
          prerelease: ${{ steps.is_prerelease.outputs.prerelease }}